Fixed Issue #107, added myself to admins list
Connor-Bernard/gradeView pull request #110
Opened 2024-02-22 19:52 UTC by somemone111

Turns out, when the admin student is changed, the projections endpoint simply isn't called. I added an admin projections endpoint, then called that endpoint in the frontend.
I also added my email to the admins category of the default config.

2024-02-22 21:03 UTC, Connor-Bernard requested changes

2024-02-23 04:00 UTC, somemone111 commented on api/server.js
> +    app.post('/api/admin/getStudentProjection', async (req, res) => {
I just made these commits.

2024-02-23 11:17 UTC, Connor-Bernard requested changes

2024-02-23 11:17 UTC, Connor-Bernard commented on api/server.js
> +    app.get('/api/admin/getStudentProjection', async (req, res) => {
`get` in the route is repetitive.  The only way we can trigger this endpoint is with a get request.

2024-02-25 02:58 UTC, Connor-Bernard commented
Can you also change the name of the PR to explain what it does (eg: fix grading bins)

2024-02-25 03:01 UTC, Connor-Bernard approved these changes
LGTM

2024-02-25 03:03 UTC, Connor-Bernard commented
I'm going to merge this personally since the customer is requesting these features ASAP

2024-02-25 03:03 UTC, merged