finished changing apiauth to sheetsClient and changed favicon
Connor-Bernard/gradeView pull request #53
Opened 2023-03-16 18:42 UTC by adityaiyer7

closes #7 , #6

2023-03-16 18:48 UTC, Connor-Bernard requested changes
Couple of changes on files.  Nice job otherwise :)

2023-03-16 18:48 UTC, Connor-Bernard commented on api/server.js
Lets remove the commented out sheetsclient in every function

2023-03-16 18:48 UTC, Connor-Bernard commented on website/src/components/BinTable.js
Check this back out to main

2023-04-03 22:33 UTC, Connor-Bernard requested changes
I made a couple of changes for formatting and documentation.  We should move the favicon to it's own branch and PR instead of having a joined PR for the two features, but after that, this all looks good.

2023-04-06 23:15 UTC, adityaiyer7 commented
I've moved the favicon to it's own branch and created a new PR for that branch. I don't see any additional comments other than that so I'm requesting a re-review on this PR.

2024-02-11 05:08 UTC, closed without merging